from simaple.fetch.element.character import standard_character_element


def test_item_element():
    element = standard_character_element()

    with open("tests/fetch/resources/character.html", encoding="euc-kr") as f:
        html_text = f.read()

    result = element.run(html_text)
    assert result == {
        "name": "생분자",
        "level": 275,
        "overview": {
            "world": "크로아",
            "job": "마법사/아크메이지(불,독)",
            "pop": 1860,
            "guild": "Shiny",
            "meso": 169913574,
            "point": 2735,
        },
        "stat": {
            "min_damage_factor": 104185958,
            "max_damage_factor": 108527036,
            "MHP": 43438,
            "MP": 106562,
            "STR": 5044,
            "DEX": 4535,
            "INT": 52802,
            "LUK": 8138,
            "critical_damage": 75,
            "boss_damage_multiplier": 303,
            "ignored_defence": 96,
            "immunity": 45,
            "stance": 100,
            "armor": 21769,
            "speed": 140,
            "jump": 123,
            "starforce": 345,
            "honor_point": 646603,
            "arcaneforce": 1360,
        },
        "ability": {
            "STR_static": 0,
            "DEX_static": 0,
            "INT_static": 0,
            "LUK_static": 0,
            "MHP": 0,
            "MMP": 0,
            "attack_power": 0,
            "magic_attack": 0,
            "critical_rate": 20.0,
            "attackSpeed": 0,
            "strToDEX": 0,
            "dexToSTR": 0,
            "intToLUK": 0,
            "lukToDEX": 0,
            "relativeAttackPower": 0,
            "relativeMagicAttack": 0,
            "MHP_multiplier": 0,
            "MMP_multiplier": 0,
            "boss_damage_multiplier": 0,
            "abnormal_status_damage_multiplier": 7.0,
            "cooldown_reset_chance": 0,
            "passiveSkill": 0,
            "multiTarget": 0,
            "buff_duration": 50.0,
        },
        "hyperstat": {
            "STR_static": 0,
            "DEX_static": 0,
            "INT_static": 150.0,
            "LUK_static": 60.0,
            "MHP_multiplier": 0,
            "MMP_multiplier": 0,
            "DF": 0,
            "PP": 0,
            "critical_rate": 13.0,
            "critical_damage": 12.0,
            "ignored_defence": 36.0,
            "damage_multiplier": 36.0,
            "boss_damage_multiplier": 43.0,
            "immunity": 0,
            "attack_power": 18.0,
            "magic_attack": 18.0,
            "arcaneforce": 0,
        },
        "propensity": {
            "카리스마": 100,
            "통찰력": 100,
            "의지": 100,
            "손재주": 100,
            "감성": 100,
            "매력": 100,
        },
    }
