/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Tier = string;
export type UnionBlockCount = number;
export type LinkCount = number;
export type ArtifactLevel = number;
export type PropensityLevel = number;
export type JobType =
  | "hero"
  | "darkknight"
  | "paladin"
  | "bishop"
  | "archmagefb"
  | "archmagetc"
  | "nightlord"
  | "shadower"
  | "dualblade"
  | "bowmaster"
  | "sniper"
  | "pathfinder"
  | "corsair"
  | "buccaneer"
  | "cannoneer"
  | "soulmaster"
  | "flamewizard"
  | "windbreaker"
  | "nightwalker"
  | "striker"
  | "mihile"
  | "demonavenger"
  | "demonslayer"
  | "battlemage"
  | "wildhunter"
  | "mechanic"
  | "zenon"
  | "blaster"
  | "evan"
  | "luminous"
  | "mercedes"
  | "phantom"
  | "eunwol"
  | "aran"
  | "kaiser"
  | "kain"
  | "cadena"
  | "angelicbuster"
  | "adele"
  | "illium"
  | "ark"
  | "lara"
  | "hoyoung"
  | "khali"
  | "zero"
  | "kinesis"
  | "virtual_maplestory_m";
export type Level = number;
export type PassiveSkillLevel = number;
export type CombatOrdersLevel = number;
export type WeaponPureAttackPower = number;
export type UseDoping = boolean;
export type Armor = number;
export type MobLevel = number;
export type ForceAdvantage = number;
export type VSkillLevel = number;
export type HexaSkillLevel = number;
export type HexaMasteryLevel = number;
export type VImprovementsLevel = number;
export type HexaImprovementsLevel = number;
export type WeaponAttackPower = number;

export interface BaselineEnvironmentProvider {
  tier: Tier;
  union_block_count?: UnionBlockCount;
  link_count?: LinkCount;
  artifact_level: ArtifactLevel;
  propensity_level?: PropensityLevel;
  jobtype: JobType;
  level: Level;
  passive_skill_level: PassiveSkillLevel;
  combat_orders_level: CombatOrdersLevel;
  weapon_pure_attack_power?: WeaponPureAttackPower;
  use_doping?: UseDoping;
  armor?: Armor;
  mob_level?: MobLevel;
  force_advantage?: ForceAdvantage;
  v_skill_level?: VSkillLevel;
  hexa_skill_level?: HexaSkillLevel;
  hexa_mastery_level?: HexaMasteryLevel;
  v_improvements_level?: VImprovementsLevel;
  hexa_improvements_level?: HexaImprovementsLevel;
  weapon_attack_power?: WeaponAttackPower;
  [k: string]: unknown;
}
