/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Damage = number;
export type Start = number;
export type End = number;

export interface MaximumDealingIntervalResult {
  damage: Damage;
  start: Start;
  end: End;
}
