// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  CastStatement = 3,
  Repetition = 4,
  Number = 5,
  Quotedstring = 6,
  ElapseStatement = 7
