// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Statement = 3,
  CastStatement = 4,
  Repetition = 5,
  Number = 6,
  QuotedString = 7,
  ElapseStatement = 8,
  ResolveStatement = 9,
  KeydownStopStatement = 10
