// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {simapleHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQVQPOOObQPO'#C`OgQPO'#C_OlQPO'#C_OqQPO'#CcOOQO'#C^'#C^OOQO'#Cd'#CdQVQPOOOOQO,58z,58zOOQO,58y,58yOvQPO,58yOOQO,58},58}OOQO-E6b-E6bOOQO1G.e1G.e",
  stateData: "{~OZOS~O[PO]QO^SO~OTWO~OUXO~O]YO~OTZO~OU]O~O",
  goto: "lXPPY^bPP^fTUOVTTOVTROVQVOR[V",
  nodeNames: "⚠ Program Statement CastStatement Repetition Number Quotedstring ElapseStatement",
  maxTerm: 14,
  propSources: [simapleHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "${~RZXYtYZt]^tpqtrsy}!O!n!Q!R!w!R![#_!e!f#j!g!h$R#l#m$v~yOZ~~|VOYyZryrs!cs#Oy#P;'Sy;'S;=`!h<%lOy~!hOU~~!kP;=`<%ly~!qQ!Q!R!w!R![#_~!|PT~!O!P#P~#SP!Q![#V~#[PT~!Q![#V~#dQT~!O!P#P!Q![#_~#mP!c!d#p~#sP!u!v#v~#yP!v!w#|~$RO]~~$UP!n!o$X~$[P!c!d$_~$bP!r!s$e~$hP!u!v$k~$nP!g!h$q~$vO^~~${O[~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
